[package]
name = "fixie"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "fixie"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

fixie_integrity = { path = "../../integrity/fixie", package = "fixie_integrity" }
